#,---.                   |     |
#|    ,--.,---.,---.,---.| ,-. |,---.,--.
#|    |   |---'|---'|---'| | | |,---||
#'---'`   `---'`---''   `-`  `-``---^`
lang:
  - zh-CN
  - en-US
bungeecord:
  enable: false
  defaultgame: default
  lobby: hub
  motd:
    unsetted: "§c插件未配置"
    waiting: "§a等待中"
    full: "§c已满人"
    started: "§6已开始"
    resetting: "§b正在重置..."

# what do you want to use for data storage
#
# support: sql,yaml
# default: yaml
#
# if sql used, please config database
dataSource: yaml

database:
  host: localhost
  port: 3306
  username: root
  password: root_password
  database: CreepWar