blocks:
  LAPIS_ORE: 29
  IRON_ORE: 92
  OAK_LOG: 140
  OAK_LEAVE: 38
  HAY_BLOCK: 17
  REDSTONE_ORE: 11
  GOLD_ORE: 18
  WATER: 14
  COAL_ORE: 21
  DIAMOND_ORE: 7
  ENCHANTMENT_TABLE: 6
  GRAVEL: 12
  ANVIL: 3